translate:
  # 配置采用哪种第三方实现 aliyun/baidu/tencent
  service: tencent
  deepl:
    key: ""
  baidu:
    appId: ""
    key: ""
    api: http://api.fanyi.baidu.com/api/trans/vip/translate
  aliyun:
    keyId: ""
    keySecret: ""
    endpoint: "mt.cn-hangzhou.aliyuncs.com"
  tencent:
    keyId: ""
    keySecret: ""
    region: "ap-shanghai"
    projectId: 0